import { GoogleGenAI } from '@google/genai'
import { env } from '@/lib/env'
import { createAdminClient } from '@/lib/supabase/admin'
import {
  AiReviewResponseSchema,
  DOCUMENT_FLAG_REASON_KEYS,
  type DocumentFlagReasonKey,
} from '@/lib/validations/documents'

export interface AiReviewResult {
  status: 'clear' | 'flagged' | 'error'
  reasonKey?: DocumentFlagReasonKey
}

const ai = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY })

// Builds a document-type-specific prompt that explicitly enumerates the valid reasonKeys.
// The model is instructed to return ONLY a JSON object — no prose, no markdown fences.
function buildPrompt(documentType: 'passport' | 'proof_of_address' | 'signed_poa'): string {
  const allKeys = DOCUMENT_FLAG_REASON_KEYS.join(', ')

  if (documentType === 'passport') {
    return `You are a document verification assistant for Portuguese NIF applications. Analyze this passport image.

Check:
1. Is this the photo page of a valid passport? (not a driving licence, national ID card, or any other document)
2. Is the image clear enough to read all text and the photo?
3. Is the passport currently valid (expiry date in the future)?

Return ONLY a JSON object — no other text, no markdown:
- All checks pass: {"status":"clear"}
- Specific issue found: {"status":"flagged","reasonKey":"<key>"} where <key> is exactly one of: ${allKeys}
- Image cannot be analyzed at all: {"status":"error"}

Key definitions:
- passport_expired: expiry date is visible and has already passed
- passport_blurry: text or photo is unreadable due to blur or poor focus
- passport_obscured: part of the document is cut off, covered, or folded
- passport_wrong_document: this is not a passport photo page (wrong document type)`
  }

  if (documentType === 'signed_poa') {
    return `You are a document verification assistant for Portuguese NIF applications. Analyze this signed Power of Attorney (POA) document.

This document was generated by RemoteNIF and sent to the applicant to sign by hand. It authorizes a fiscal representative to obtain a Portuguese NIF on their behalf.

Check:
1. Is this actually a POA or authorization document? (not a passport, utility bill, or unrelated document)
2. Is there at least one visible handwritten signature on the document?
3. Does the document appear to have the required fields filled in (name, date, or similar)?

Return ONLY a JSON object — no other text, no markdown:
- All checks pass: {"status":"clear"}
- Specific issue found: {"status":"flagged","reasonKey":"<key>"} where <key> is exactly one of: ${allKeys}
- Image cannot be analyzed at all: {"status":"error"}

Key definitions:
- poa_unsigned: no handwritten signature is visible on the document
- poa_wrong_document: this is not a POA or authorization document (e.g. passport or utility bill uploaded by mistake)
- poa_incomplete: the document appears to be the correct type but key fields are blank or not filled in`
  }

  return `You are a document verification assistant for Portuguese NIF applications. Analyze this proof of address document.

Accepted types: electricity bill, water bill, gas bill, bank statement, rental or lease agreement, official government letter with address. Phone bills and TV/cable bills are NOT accepted.

Check:
1. Is this an accepted proof of address document type?
2. Is it dated within the last 3 months?
3. Is the image clear and readable?
4. Does the document appear to be in a personal name (not a company name)?

Return ONLY a JSON object — no other text, no markdown:
- All checks pass: {"status":"clear"}
- Specific issue found: {"status":"flagged","reasonKey":"<key>"} where <key> is exactly one of: ${allKeys}
- Image cannot be analyzed at all: {"status":"error"}

Key definitions:
- address_too_old: document is dated more than 3 months ago
- address_type_not_accepted: phone bill, TV/cable bill, or other non-accepted document type
- address_blurry: text is unreadable due to blur or poor image quality
- address_wrong_document: this does not appear to be a proof of address document
- address_name_mismatch: document appears to be in a business or company name, not a personal name`
}

/**
 * Downloads a document from Supabase Storage and sends it to Gemini for review.
 * Returns a structured result validated against AiReviewResponseSchema.
 * Any failure (download, parse, or schema mismatch) returns { status: 'error' }.
 */
export async function reviewDocumentWithAI(
  filePath: string,
  mimeType: string,
  documentType: 'passport' | 'proof_of_address' | 'signed_poa',
): Promise<AiReviewResult> {
  try {
    // Download from Supabase Storage via admin client (bypasses RLS)
    const supabase = createAdminClient()
    const { data: blob, error: downloadError } = await supabase.storage
      .from('documents')
      .download(filePath)

    if (downloadError || !blob) {
      console.error('[gemini] Storage download failed:', downloadError)
      return { status: 'error' }
    }

    const buffer = await blob.arrayBuffer()
    const base64 = Buffer.from(buffer).toString('base64')

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: [
        {
          role: 'user',
          parts: [
            { inlineData: { mimeType, data: base64 } },
            { text: buildPrompt(documentType) },
          ],
        },
      ],
    })

    // Strip markdown code fences Gemini sometimes adds despite instructions
    const rawText = (response.text ?? '').trim()
    const jsonText = rawText
      .replace(/^```(?:json)?\s*/i, '')
      .replace(/\s*```$/, '')
      .trim()

    let parsed: unknown
    try {
      parsed = JSON.parse(jsonText)
    } catch {
      console.error('[gemini] Response is not valid JSON:', rawText)
      return { status: 'error' }
    }

    // Validate with Zod — any unexpected reasonKey or status value becomes an error,
    // never a raw string surfaced to the user
    const validated = AiReviewResponseSchema.safeParse(parsed)
    if (!validated.success) {
      console.error('[gemini] Response failed schema validation:', parsed, validated.error.issues)
      return { status: 'error' }
    }

    return {
      status: validated.data.status,
      reasonKey: validated.data.reasonKey,
    }
  } catch (err) {
    console.error('[gemini] Unexpected error during document review:', err)
    return { status: 'error' }
  }
}
